package com.cucumberforge.plugin.util;

import com.cucumberforge.plugin.model.FeatureFileModel.StepKeyword;
import com.cucumberforge.plugin.model.FeatureFileModel.StepModel;
import com.cucumberforge.plugin.model.StepDefinitionModel.StepParameter;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Generates Java step definition code from Gherkin steps.
 */
public final class JavaCodeGenerator {

    private static final Pattern QUOTED_STRING_PATTERN = Pattern.compile("\"([^\"]+)\"");
    private static final Pattern INTEGER_PATTERN = Pattern.compile("\\b(\\d+)\\b");
    private static final Pattern FLOAT_PATTERN = Pattern.compile("\\b(\\d+\\.\\d+)\\b");
    private static final Pattern PLACEHOLDER_PATTERN = Pattern.compile("<([^>]+)>");

    private JavaCodeGenerator() {}

    /**
     * Generate a full step definition Java class from a list of steps.
     */
    public static String generateStepDefinitionClass(String packageName, String className,
                                                     List<StepModel> steps) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");

        // Imports
        Set<String> imports = new LinkedHashSet<>();
        imports.add("io.cucumber.java.en.Given");
        imports.add("io.cucumber.java.en.When");
        imports.add("io.cucumber.java.en.Then");
        imports.add("io.cucumber.java.en.And");
        imports.add("io.cucumber.java.en.But");

        boolean hasDataTable = steps.stream().anyMatch(s -> s.getDataTable() != null);
        if (hasDataTable) {
            imports.add("io.cucumber.datatable.DataTable");
        }

        imports.add("org.springframework.beans.factory.annotation.Autowired");

        for (String imp : imports) {
            sb.append("import ").append(imp).append(";\n");
        }

        sb.append("\n");
        sb.append("/**\n");
        sb.append(" * Step definitions generated by CucumberForge.\n");
        sb.append(" */\n");
        sb.append("public class ").append(className).append(" {\n\n");

        // Track used method names to avoid duplicates
        Set<String> usedMethodNames = new HashSet<>();

        for (StepModel step : steps) {
            String methodCode = generateStepMethod(step, usedMethodNames);
            sb.append(methodCode).append("\n");
        }

        sb.append("}\n");
        return sb.toString();
    }

    /**
     * Generate a single step definition method.
     */
    public static String generateStepMethod(StepModel step, Set<String> usedMethodNames) {
        StringBuilder sb = new StringBuilder();
        String annotation = resolveAnnotation(step.getKeyword());
        String stepText = step.getText();

        // Detect and replace parameters in the step text
        List<StepParameter> params = new ArrayList<>();
        String cucumberExpression = convertToCucumberExpression(stepText, params);

        // Generate method name
        String methodName = toMethodName(stepText);
        methodName = ensureUniqueName(methodName, usedMethodNames);
        usedMethodNames.add(methodName);

        // Build method signature
        sb.append("    @").append(annotation).append("(\"").append(escapeJava(cucumberExpression)).append("\")\n");
        sb.append("    public void ").append(methodName).append("(");

        // Parameters
        List<String> paramDeclarations = new ArrayList<>();
        for (StepParameter param : params) {
            paramDeclarations.add(param.getType() + " " + param.getName());
        }
        if (step.getDataTable() != null) {
            paramDeclarations.add("DataTable dataTable");
        }
        sb.append(String.join(", ", paramDeclarations));

        sb.append(") {\n");
        sb.append("        // TODO: Implement step\n");
        sb.append("        throw new io.cucumber.java.PendingException();\n");
        sb.append("    }\n");

        return sb.toString();
    }

    /**
     * Generate a Cucumber runner class for JUnit 5.
     */
    public static String generateRunnerJUnit5(String packageName, String className) {
        return "package " + packageName + ";\n\n" +
                "import org.junit.platform.suite.api.ConfigurationParameter;\n" +
                "import org.junit.platform.suite.api.IncludeEngines;\n" +
                "import org.junit.platform.suite.api.SelectClasspathResource;\n" +
                "import org.junit.platform.suite.api.Suite;\n\n" +
                "import static io.cucumber.junit.platform.engine.Constants.GLUE_PROPERTY_NAME;\n" +
                "import static io.cucumber.junit.platform.engine.Constants.PLUGIN_PROPERTY_NAME;\n\n" +
                "@Suite\n" +
                "@IncludeEngines(\"cucumber\")\n" +
                "@SelectClasspathResource(\"features\")\n" +
                "@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = \"" + packageName + "\")\n" +
                "@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = \"pretty, html:target/cucumber-reports.html\")\n" +
                "public class " + className + " {\n" +
                "}\n";
    }

    /**
     * Generate a Cucumber runner class for JUnit 4.
     */
    public static String generateRunnerJUnit4(String packageName, String className) {
        return "package " + packageName + ";\n\n" +
                "import io.cucumber.junit.Cucumber;\n" +
                "import io.cucumber.junit.CucumberOptions;\n" +
                "import org.junit.runner.RunWith;\n\n" +
                "@RunWith(Cucumber.class)\n" +
                "@CucumberOptions(\n" +
                "    features = \"src/test/resources/features\",\n" +
                "    glue = \"" + packageName + "\",\n" +
                "    plugin = {\"pretty\", \"html:target/cucumber-reports.html\"}\n" +
                ")\n" +
                "public class " + className + " {\n" +
                "}\n";
    }

    /**
     * Generate Spring Cucumber configuration class.
     */
    public static String generateSpringConfig(String packageName) {
        return "package " + packageName + ".config;\n\n" +
                "import io.cucumber.spring.CucumberContextConfiguration;\n" +
                "import org.springframework.boot.test.context.SpringBootTest;\n" +
                "import org.springframework.test.context.ActiveProfiles;\n\n" +
                "@CucumberContextConfiguration\n" +
                "@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)\n" +
                "@ActiveProfiles(\"test\")\n" +
                "public class CucumberSpringConfiguration {\n" +
                "}\n";
    }

    /**
     * Generate a Test Data Builder class for a given entity.
     */
    public static String generateTestDataBuilder(String packageName, String entityName,
                                                  Map<String, String> fields) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(packageName).append(".support;\n\n");
        sb.append("import java.util.concurrent.ThreadLocalRandom;\n\n");
        sb.append("/**\n");
        sb.append(" * Builder for creating test instances of ").append(entityName).append(".\n");
        sb.append(" * Generated by CucumberForge.\n");
        sb.append(" */\n");
        sb.append("public class ").append(entityName).append("Builder {\n\n");

        // Fields with defaults
        for (Map.Entry<String, String> field : fields.entrySet()) {
            String defaultValue = getDefaultValue(field.getValue());
            sb.append("    private ").append(field.getValue()).append(" ").append(field.getKey())
                    .append(" = ").append(defaultValue).append(";\n");
        }
        sb.append("\n");

        // Private constructor
        sb.append("    private ").append(entityName).append("Builder() {}\n\n");

        // Static factory
        sb.append("    public static ").append(entityName).append("Builder builder() {\n");
        sb.append("        return new ").append(entityName).append("Builder();\n");
        sb.append("    }\n\n");

        // Fluent setters
        for (Map.Entry<String, String> field : fields.entrySet()) {
            String name = field.getKey();
            String type = field.getValue();
            sb.append("    public ").append(entityName).append("Builder ").append(name)
                    .append("(").append(type).append(" ").append(name).append(") {\n");
            sb.append("        this.").append(name).append(" = ").append(name).append(";\n");
            sb.append("        return this;\n");
            sb.append("    }\n\n");
        }

        // Build method
        sb.append("    public ").append(entityName).append(" build() {\n");
        sb.append("        ").append(entityName).append(" entity = new ").append(entityName).append("();\n");
        for (String fieldName : fields.keySet()) {
            String setter = "set" + capitalize(fieldName);
            sb.append("        entity.").append(setter).append("(this.").append(fieldName).append(");\n");
        }
        sb.append("        return entity;\n");
        sb.append("    }\n\n");

        // Random factory
        sb.append("    public static ").append(entityName).append(" random() {\n");
        sb.append("        return builder()\n");
        for (Map.Entry<String, String> field : fields.entrySet()) {
            String randomValue = getRandomExpression(field.getValue(), field.getKey());
            sb.append("            .").append(field.getKey()).append("(").append(randomValue).append(")\n");
        }
        sb.append("            .build();\n");
        sb.append("    }\n");

        sb.append("}\n");
        return sb.toString();
    }

    /**
     * Generate Testcontainers configuration class.
     */
    public static String generateTestcontainersConfig(String packageName, String dbType, String image) {
        String containerClass;
        String importStr;

        switch (dbType.toLowerCase()) {
            case "postgresql":
                containerClass = "PostgreSQLContainer";
                importStr = "org.testcontainers.containers.PostgreSQLContainer";
                break;
            case "mysql":
                containerClass = "MySQLContainer";
                importStr = "org.testcontainers.containers.MySQLContainer";
                break;
            case "mongodb":
                containerClass = "MongoDBContainer";
                importStr = "org.testcontainers.containers.MongoDBContainer";
                break;
            default:
                containerClass = "PostgreSQLContainer";
                importStr = "org.testcontainers.containers.PostgreSQLContainer";
                break;
        }

        return "package " + packageName + ".config;\n\n" +
                "import " + importStr + ";\n" +
                "import org.springframework.test.context.DynamicPropertyRegistry;\n" +
                "import org.springframework.test.context.DynamicPropertySource;\n" +
                "import org.testcontainers.junit.jupiter.Container;\n" +
                "import org.testcontainers.junit.jupiter.Testcontainers;\n\n" +
                "@Testcontainers\n" +
                "public class TestcontainersConfiguration {\n\n" +
                "    @Container\n" +
                "    static final " + containerClass + "<?> container = new " + containerClass + "<>(\"" + image + "\")\n" +
                "            .withReuse(true);\n\n" +
                "    @DynamicPropertySource\n" +
                "    static void configureProperties(DynamicPropertyRegistry registry) {\n" +
                "        registry.add(\"spring.datasource.url\", container::getJdbcUrl);\n" +
                "        registry.add(\"spring.datasource.username\", container::getUsername);\n" +
                "        registry.add(\"spring.datasource.password\", container::getPassword);\n" +
                "    }\n" +
                "}\n";
    }

    // =================== Utility methods ===================

    /**
     * Convert a Gherkin step text to a Cucumber expression with typed placeholders.
     */
    static String convertToCucumberExpression(String text, List<StepParameter> outParams) {
        String result = text;
        int paramIndex = 0;

        // Replace quoted strings → {string}
        Matcher stringMatcher = QUOTED_STRING_PATTERN.matcher(result);
        while (stringMatcher.find()) {
            outParams.add(new StepParameter("param" + paramIndex, "String", "{string}"));
            paramIndex++;
        }
        result = QUOTED_STRING_PATTERN.matcher(result).replaceAll("{string}");

        // Replace floats → {float} (before integers to avoid partial match)
        Matcher floatMatcher = FLOAT_PATTERN.matcher(result);
        while (floatMatcher.find()) {
            outParams.add(new StepParameter("param" + paramIndex, "double", "{float}"));
            paramIndex++;
        }
        result = FLOAT_PATTERN.matcher(result).replaceAll("{float}");

        // Replace integers → {int}
        Matcher intMatcher = INTEGER_PATTERN.matcher(result);
        while (intMatcher.find()) {
            outParams.add(new StepParameter("param" + paramIndex, "int", "{int}"));
            paramIndex++;
        }
        result = INTEGER_PATTERN.matcher(result).replaceAll("{int}");

        // Replace <placeholders> → {string} (for Scenario Outline)
        Matcher placeholderMatcher = PLACEHOLDER_PATTERN.matcher(result);
        while (placeholderMatcher.find()) {
            outParams.add(new StepParameter(toCamelCase(placeholderMatcher.group(1)), "String", "{string}"));
            paramIndex++;
        }
        result = PLACEHOLDER_PATTERN.matcher(result).replaceAll("{string}");

        return result;
    }

    static String resolveAnnotation(StepKeyword keyword) {
        switch (keyword) {
            case GIVEN: return "Given";
            case WHEN:  return "When";
            case THEN:  return "Then";
            case AND:   return "And";
            case BUT:   return "But";
            default:    return "Given";
        }
    }

    static String toMethodName(String stepText) {
        // Remove quotes, params, and non-alpha characters
        String cleaned = stepText
                .replaceAll("\"[^\"]*\"", "value")
                .replaceAll("<[^>]*>", "param")
                .replaceAll("[^a-zA-Z0-9\\s]", "")
                .trim();

        String[] words = cleaned.split("\\s+");
        if (words.length == 0) return "step";

        StringBuilder sb = new StringBuilder(words[0].toLowerCase());
        for (int i = 1; i < words.length && i < 8; i++) {
            sb.append(capitalize(words[i].toLowerCase()));
        }
        return sb.toString();
    }

    private static String ensureUniqueName(String name, Set<String> used) {
        if (!used.contains(name)) return name;
        int counter = 2;
        while (used.contains(name + counter)) counter++;
        return name + counter;
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private static String toCamelCase(String s) {
        String[] parts = s.split("[_\\s-]+");
        StringBuilder sb = new StringBuilder(parts[0].toLowerCase());
        for (int i = 1; i < parts.length; i++) {
            sb.append(capitalize(parts[i].toLowerCase()));
        }
        return sb.toString();
    }

    private static String escapeJava(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String getDefaultValue(String type) {
        switch (type) {
            case "String":  return "\"test\"";
            case "int":
            case "Integer": return "1";
            case "long":
            case "Long":    return "1L";
            case "double":
            case "Double":  return "1.0";
            case "float":
            case "Float":   return "1.0f";
            case "boolean":
            case "Boolean": return "true";
            default:        return "null";
        }
    }

    private static String getRandomExpression(String type, String fieldName) {
        switch (type) {
            case "String":
                return "\"" + fieldName + "_\" + ThreadLocalRandom.current().nextInt(10000)";
            case "int":
            case "Integer":
                return "ThreadLocalRandom.current().nextInt(1, 1000)";
            case "long":
            case "Long":
                return "ThreadLocalRandom.current().nextLong(1, 100000)";
            case "double":
            case "Double":
                return "ThreadLocalRandom.current().nextDouble(0.01, 999.99)";
            case "boolean":
            case "Boolean":
                return "ThreadLocalRandom.current().nextBoolean()";
            default:
                return "null";
        }
    }
}
